//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeasDepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedView
    {
        public string dCategory { get; set; }
        public string dProductInfo { get; set; }
        public string dSNum { get; set; }
        public string dReason { get; set; }
        public Nullable<System.DateTime> dDate { get; set; }
        public string dName { get; set; }
        public string dSurname { get; set; }
        public string dMethod { get; set; }
    }
}
