//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeasDepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainView
    {
        public string dCategory { get; set; }
        public string dInfo { get; set; }
        public string dSN { get; set; }
        public string dHEASID { get; set; }
        public string dDescription { get; set; }
    }
}
